### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by troggy**

### CODE REVIEW

**Comment by emesik** [comment]
Could you use the original page size (5×7cm), please?

Or, if that's a problem, please pass the Russian text here and I'll paste it into the template.

PS: The original font is Century Gothic.

**Comment by troggy** [comment]
I had troubles with PNG export with original page size (I use Inkscape). I
will try one more time and will send you the text if failed again.

**Comment by troggy** [comment]
I've recreated the translation keeping the original source size. @emesik please check.

**Comment by emesik** [comment]
Wonderful! Thanks!

**Pull request merged**
